# webservice
web:
  host:  0.0.0.0
  port:  9000
  debug: false

# log
log:
  dir:        /home/justin/workspace/src/dienlanhphongvan-cdn/log
  levelDebug: false 

# resource directory where store bot original and cached images
resource:
  rootDir: /home/justin/workspace/src/cdn/master/resource

# storate service: serve original images, handle upload images
# if storage have role slave, storage.address is required
storageRoleSlave: false
storage:
  address: 

# pot service: serve original images, cached images. It will download original images from storage 
pot:
  address: http://localhost:8930

# slave service: serve original images, cached images. It will download original and cached images from pot service.
slave:
  address: http://localhost:8910

# imgx service: image processing service
imgx:
  address: http://localhost:8920

# cjpeg: convert image to progressive image.
compressor :
  enable: true
  exec:   /opt/mozjpeg/bin/cjpeg

# convert: try to coverage invalid image.
convertor :
  enable: true
  exec:   /usr/local/bin/convert

# newrelic
newRelic:
  enable:  false
  name:    debug 
  license: cd50f97e8d90f2565cccc064d374756bda72effe

# whitelist
whiteList:
